CLOSURE      = java -jar /usr/local/bin/compiler.jar
CLOSURE_OPTS = --compilation_level SIMPLE_OPTIMIZATIONS

lessons:
	$(CLOSURE) $(CLOSURE_OPTS) \
	--js_output_file lessons.js \
	--js units.js \
	--js units/1/01-hello-world.js \
	--js units/1/02-headers.js \
	--js units/1/03-attributes.js \
	--js units/1/04-self-closing.js \
	--js units/1/05-html-entities.js \
	--js units/2/01-links.js \
	--js units/2/02-images.js \
	--js units/2/03-paths.js \
	--js units/2/04-comments.js \
	--js units/2/05-breaks.js \
	--js units/3/01-bold.js \
	--js units/3/02-italics.js \
	--js units/3/03-super.js \
	--js units/3/04-styles.js \
	--js units/4/01-lists.js \
	--js units/4/02-nested-lists.js \
	--js units/4/03-tables.js \
	--js units/5/01-style.js \
	--js units/5/02-more-styles.js \
	--js units/5/03-style-tag.js \
	--js units/5/04-classes.js \
	--js units/5/05-span.js \
	--js units/7/01-forms.js \
	--js units/7/02-names.js \
	--js units/7/03-radio-check.js \
	--js units/7/04-submit.js \
	--js units/7/05-select.js